nodes:
  n1: [r1]
  n2: [r2]
  n3: [r3]
  n4: [r4]
  n5: [r5]
  n6: [r6]

edges:
  - [n1, n2]
  - [n1, n3]
  - [n2, n4]
  - [n2, n5]
  - [n5, n6]

resources:
  - r1
  - r2
  - r3
  - r4
  - r5
  - r6

min_degree: 1